spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: Morsko11
    driver-class-name: org.postgresql.Driver

    jpa:
      show-sql: true
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081

